pluginManagement {
    repositories {
        google()
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven { url = uri('../build/maven-repo') }
        google()
        mavenCentral()
    }
}

rootProject.name = 'hd-wallet-kit-kmp-consumer-smoke'
